import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import Providers from "@/lib/povider";
import CartSidebar from "@/components/ui/cart-sidebar";
import SmoothScrollProvider from "@/providers/smooth-scroll-provider";
import Layout from "@/components/layout/layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const path = usePathname();
  // const pathName = ["/dashboard"];
  // if (pathName.includes(path)) return children;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <SmoothScrollProvider>
            <Layout>{children}</Layout>
          </SmoothScrollProvider>
        </Providers>
      </body>
    </html>
  );
}
