import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/lib/povider";
import SmoothScrollProvider from "@/providers/smooth-scroll-provider";
import Layout from "@/components/layout/layout";
import QueryProvider from "@/providers/query-client-provider";
import { Toaster } from "sonner";
import { NuqsProvider } from "@/providers/nuqs-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const path = usePathname();
  // const pathName = ["/dashboard"];
  // if (pathName.includes(path)) return children;

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <Providers>
            <SmoothScrollProvider>
              <NuqsProvider>
                <Layout>{children}</Layout>
              </NuqsProvider>
            </SmoothScrollProvider>
          </Providers>
        </QueryProvider>
        <Toaster richColors />
      </body>
    </html>
  );
}
