export const endpoints = {
  auth: {
    login: "/auth/login",
    signup: "/auth/signup",
    refresh: "/auth/refresh",
    username: "/auth/username",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
    forgotUsername: "/auth/forgot-username",
    resetUsername: "/auth/reset-username",
  },
  profile: "/users/me",
  files: {
    getFiles: "/upload",
    deleteKey: "/upload/s3",
    preSignedUrl: "/upload/presigned-url",
    preSignedUrls: "/upload/presigned-urls",
  },
  carts: { getAll: "/carts" },
  orders: { getAll: "/orders" },
  packages: { getAll: "/packages" },
  addresses: { getAll: "/addresses" },
  categories: { getAll: "/categories" },
  products: { getAll: "/products" },
  books: { getAll: "/books" },
  users: { getAll: "/users" },
};
